name: docs

on:
  pull_request:
    branches:
      - sphinx-docs
      - develop
      - master
  push:
    branches:
      - sphinx-docs
      - develop

jobs:
  build-and-deploy-pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -q -r docs/requirements.txt

      - name: Build docs
        run: |
          sphinx-build -W --keep-going -b html -d docs/_build/doctrees docs/source docs/_build/html
          mv -v docs/_build/html public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
